# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(661, 496)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 160, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.openserver = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.openserver.setObjectName("openserver")
        self.verticalLayout.addWidget(self.openserver)
        self.displayQR = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.displayQR.setObjectName("displayQR")
        self.verticalLayout.addWidget(self.displayQR)
        self.plugin_config = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.plugin_config.setObjectName("plugin_config")
        self.verticalLayout.addWidget(self.plugin_config)
        self.run_plugin = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.run_plugin.setObjectName("run_plugin")
        self.verticalLayout.addWidget(self.run_plugin)
        self.importwaveforms = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.importwaveforms.setObjectName("importwaveforms")
        self.verticalLayout.addWidget(self.importwaveforms)
        self.run_waveforms = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.run_waveforms.setObjectName("run_waveforms")
        self.verticalLayout.addWidget(self.run_waveforms)
        self.clos = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.clos.setObjectName("clos")
        self.verticalLayout.addWidget(self.clos)
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(425, 20, 231, 461))
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 470, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 20, 158, 51))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(190, 80, 54, 12))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(300, 70, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(200, 70, 91, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.openserver.setText(_translate("Dialog", "开启服务端 "))
        self.displayQR.setText(_translate("Dialog", "显示二维码 "))
        self.plugin_config.setText(_translate("Dialog", "插件配置 "))
        self.run_plugin.setText(_translate("Dialog", "启动插件 "))
        self.importwaveforms.setText(_translate("Dialog", "导入波形 "))
        self.run_waveforms.setText(_translate("Dialog", "播放波形"))
        self.clos.setText(_translate("Dialog", "关闭程序 "))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">By:凯凯同学 </p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">郊狼惩罚器</span> v1.0</p><p align=\"center\"><br/></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "客户端连接地址："))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
